# Generated by Django 2.0.3 on 2024-03-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
