# Generated by Django 2.0.3 on 2024-03-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='lattitude',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
