# Generated by Django 2.0.3 on 2024-03-14 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240313_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='locate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(default=1, max_length=50)),
                ('longitude', models.CharField(default=1, max_length=50)),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver')),
            ],
        ),
    ]
