# Generated by Django 2.0.3 on 2024-03-14 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_std_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_status',
            name='DRIVER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Driver'),
        ),
    ]
